package com.janadhikar.memory

import java.text.Normalizer

/**
 * SentencePiece UNIGRAM tokenizer (XLM-R flavour) — pure Kotlin, offline,
 * deterministic. Matches HuggingFace's XLMRobertaTokenizer for
 * paraphrase-multilingual-MiniLM-L12-v2.
 *
 * Correctness is enforced by SentencePieceTokenizerTest against golden
 * vectors generated by knowledge-pipeline/export_tflite.py with the reference
 * tokenizer — if the two ever disagree, the test fails and the build is red.
 *
 * Vocab rows carry the FINAL HuggingFace ids (fairseq offset already applied
 * by the pipeline) plus the unigram log-probability scores used by Viterbi.
 */
class SentencePieceTokenizer(vocabRows: Sequence<Triple<String, Int, Float>>) {

    private val idOf = HashMap<String, Int>(280_000)
    private val scoreOf = HashMap<String, Float>(280_000)
    private var minScore = 0f

    init {
        for ((token, id, score) in vocabRows) {
            idOf[token] = id
            scoreOf[token] = score
            if (score < minScore) minScore = score
        }
    }

    private val bosId = requireNotNull(idOf["<s>"]) { "vocab missing <s>" }
    private val eosId = requireNotNull(idOf["</s>"]) { "vocab missing </s>" }
    private val unkId = requireNotNull(idOf["<unk>"]) { "vocab missing <unk>" }
    private val padId = requireNotNull(idOf["<pad>"]) { "vocab missing <pad>" }

    /** Penalty for characters not covered by any piece (sentencepiece convention). */
    private val unkScore get() = minScore - 10f

    data class Encoding(val inputIds: IntArray, val attentionMask: IntArray)

    fun encode(text: String, seqLen: Int): Encoding {
        val pieces = tokenize(text)
        val ids = buildList {
            add(bosId)
            addAll(pieces.take(seqLen - 2))
            add(eosId)
        }
        return Encoding(
            inputIds = IntArray(seqLen) { i -> if (i < ids.size) ids[i] else padId },
            attentionMask = IntArray(seqLen) { i -> if (i < ids.size) 1 else 0 },
        )
    }

    /** Raw piece ids without special tokens (exposed for the parity test). */
    fun tokenize(text: String): List<Int> {
        val normalized = normalize(text)
        if (normalized.isEmpty()) return emptyList()
        return viterbi(normalized)
    }

    /**
     * nmt_nfkc approximation: NFKC + control chars to space + whitespace
     * collapse, then the SentencePiece space marker (▁).
     */
    private fun normalize(text: String): String {
        val nfkc = Normalizer.normalize(text, Normalizer.Form.NFKC)
        val cleaned = nfkc
            .map { if (it.isISOControl()) ' ' else it }
            .joinToString("")
            .replace(Regex("""\s+"""), " ")
            .trim()
        if (cleaned.isEmpty()) return ""
        return "▁" + cleaned.replace(' ', '▁')
    }

    /** Max-score segmentation over unigram piece log-probabilities. */
    private fun viterbi(s: String): List<Int> {
        val n = s.length
        val bestScore = FloatArray(n + 1) { Float.NEGATIVE_INFINITY }
        val bestPrev = IntArray(n + 1) { -1 }
        val bestPiece = arrayOfNulls<String>(n + 1)
        bestScore[0] = 0f

        for (end in 1..n) {
            val start0 = maxOf(0, end - MAX_PIECE_CHARS)
            for (start in start0 until end) {
                if (bestScore[start] == Float.NEGATIVE_INFINITY) continue
                val piece = s.substring(start, end)
                val score = scoreOf[piece] ?: continue
                val total = bestScore[start] + score
                if (total > bestScore[end]) {
                    bestScore[end] = total
                    bestPrev[end] = start
                    bestPiece[end] = piece
                }
            }
            // Unknown fallback: single char with unk penalty.
            if (bestScore[end] == Float.NEGATIVE_INFINITY && bestScore[end - 1] != Float.NEGATIVE_INFINITY) {
                bestScore[end] = bestScore[end - 1] + unkScore
                bestPrev[end] = end - 1
                bestPiece[end] = null // marks <unk>
            }
        }

        val ids = ArrayDeque<Int>()
        var pos = n
        while (pos > 0) {
            val piece = bestPiece[pos]
            ids.addFirst(if (piece == null) unkId else idOf.getValue(piece))
            pos = bestPrev[pos]
        }
        return ids.toList()
    }

    companion object {
        /** XLM-R pieces are short; bounding the window keeps Viterbi O(n·k). */
        private const val MAX_PIECE_CHARS = 24

        /** Parses `token \t hfId \t score` rows (spm_vocab.tsv). */
        fun loadVocab(lines: Sequence<String>): Sequence<Triple<String, Int, Float>> =
            lines.mapNotNull { line ->
                val parts = line.split('\t')
                if (parts.size == 3) Triple(parts[0], parts[1].toInt(), parts[2].toFloat()) else null
            }
    }
}
