package com.janadhikar.memory

import com.google.common.truth.Truth.assertThat
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assume.assumeTrue
import org.junit.BeforeClass
import org.junit.Test
import java.io.File

/**
 * PARITY GATE: the Kotlin tokenizer must reproduce HuggingFace's
 * XLMRobertaTokenizer EXACTLY on the golden vectors generated by
 * knowledge-pipeline/export_tflite.py. A single divergent id means query
 * embeddings drift from corpus embeddings — silently degraded retrieval —
 * so this failing must block the build.
 */
class SentencePieceTokenizerTest {

    @Serializable
    data class Vector(val text: String, val input_ids: List<Int>)

    @Test
    fun `kotlin tokenizer matches reference tokenizer on golden vectors`() {
        val vectorsStream = javaClass.getResourceAsStream("/tokenizer_vectors.json")
        assumeTrue(
            "tokenizer_vectors.json missing — run knowledge-pipeline/export_tflite.py",
            vectorsStream != null,
        )
        val vectors = Json.decodeFromString<List<Vector>>(
            vectorsStream!!.bufferedReader().readText(),
        )

        for (vector in vectors) {
            val encoding = tokenizer.encode(vector.text, SEQ_LEN)
            val produced = encoding.inputIds.take(vector.input_ids.size)
            assertThat(produced).isEqualTo(vector.input_ids)
            // Mask covers exactly the real tokens.
            assertThat(encoding.attentionMask.count { it == 1 })
                .isEqualTo(vector.input_ids.size)
        }
    }

    @Test
    fun `empty and whitespace-only input yields just special tokens`() {
        val encoding = tokenizer.encode("   ", SEQ_LEN)
        assertThat(encoding.attentionMask.count { it == 1 }).isEqualTo(2) // <s> </s>
    }

    companion object {
        private const val SEQ_LEN = 128

        private lateinit var tokenizer: SentencePieceTokenizer

        @JvmStatic
        @BeforeClass
        fun load() {
            val vocabFile = File("src/main/assets/models/spm_vocab.tsv")
            assumeTrue(
                "spm_vocab.tsv missing — run knowledge-pipeline/export_tflite.py",
                vocabFile.exists(),
            )
            tokenizer = vocabFile.bufferedReader().useLines {
                SentencePieceTokenizer(SentencePieceTokenizer.loadVocab(it))
            }
        }
    }
}
